export param1 := val1
param2 := val2

all:
	@echo " --------------- top makefile print start ---------------"
	make -f scripts/Makefile.build param0=val0
	@echo " ---------------- top makefile print end ----------------"
