var = kbuild

$(info --------------------- 1 --------------------)
$(info here is Makefile info!\n $(var))

$(info --------------------- 2 --------------------)
$(warning here is Makefile warning!)

$(info --------------------- 3 --------------------)
$(error "here is Makefile error!")

$(info --------------------- 4 --------------------)