mdebug          := 0
mbuild          := -f $(srctree)/scripts/Makefile.build obj
mclean          := -f $(srctree)/scripts/Makefile.clean obj

MAKE            := make --no-print-directory
Q               := @

.PHONY: FORCE
