PHONY := __build

### 打印提示信息, 打印参数指定的字符串
$(info "here is Makefile info! p0 = $(param0)")

### 打印调试信息, 相比于 info 多打印 Makefile 具体的文件名和行号
$(warning "here is Makefile warning! p0 = $(param0)")

### 打印错误信息, 并停止 Makefile 解析执行流程
# $(error "here is Makefile error! p0 = $(param0)")

__build: 
	echo $(param0)
	echo $(param1)
	echo $(param2)
